BROWSERSTACK_USERNAME = "saimakhan_OKu0xR"
BROWSERSTACK_ACCESS_KEY = "ojnKZTzpnTSWPTxpuXwn"

BROWSERSTACK_URL = f"https://{BROWSERSTACK_USERNAME}:{BROWSERSTACK_ACCESS_KEY}@hub-cloud.browserstack.com/wd/hub"
